- src/index.css
- src/pages/gift/generate/PresentGift.js
Adjusting the gift message depending wether one sends more than 1 Unit or less.
> Gift Message Amount

- package.json
- src/App.js
- src/pages/gift/about/AboutMain.js
- src/pages/gift/about/FAQ.js
- src/pages/gift/about/ProcessExplainerCard.js
- src/polkadot.scss
- yarn.lock
Closes #7 
We probably want to update the copy later on. Also not optimised for mobile yet.
> About Page

- src/components/CardHeader.js
- src/components/Divider.js
- src/pages/gift/accounts/ConnectExtension.js
- src/pages/gift/accounts/ConnectSigner.js
- src/pages/gift/claim/ClaimMain.js
- src/pages/gift/claim/Landing.js
- src/pages/gift/claim/VerifySecret.js
- src/pages/gift/claim/existing-account/ConnectExistingAccount.js
- src/pages/gift/claim/existing-account/EnterAccountAddress.js
- src/pages/gift/claim/new-account/PresentAccountPhrase.js
- src/pages/gift/claim/new-account/VerifyAccountPhrase.js
- src/pages/gift/generate/GenerateGift.js
- src/pages/gift/generate/GenerateMain.js
- src/pages/gift/generate/Landing.js
- src/pages/gift/generate/PresentGift.js
- src/polkadot.scss
These are mainly styling updates making sure the layout of the card is cohevise.
- Added a `cardText` prop to the card header, so spacing between header and descriptive text is always the same
- Made sure button aligns to the bottom (usually by making the card a flex parent and having an empty div with `flex-grow-1` as the last element before the botton)
-  For minimal cards with different options, vertically centered the buttons
- Removed border from card, made sure borders are the same gray etc.
> Styling updates

- src/components/CustomButton.js
- src/components/LinkButton.js
- src/pages/gift/claim/Claimed.js
- src/pages/gift/claim/Landing.js
- src/pages/gift/generate/ConnectAccount.js
- src/pages/gift/generate/Landing.js
- src/pages/gift/generate/PresentGift.js
- src/polkadot.scss
Just some button positioning, and changing Message page so that we don't have three primary buttons next to each other.
> Button Spacing

- src/pages/gift/about/AboutMain.js
- src/pages/gift/claim/ClaimMain.js
- src/pages/gift/generate/GenerateMain.js
- src/polkadot.scss
- src/scss/_bg.scss
- src/scss/_variables.scss
Taking the animated gradient background from #47 
Making the modal card slightly smaller and position it closer to the top
> Background gradient

- package.json
- src/pages/gift/claim/new-account/DownloadJson.js
- src/pages/gift/claim/new-account/DownloadJsonOption.js
- src/pages/gift/claim/new-account/NewAccountMain.js
- yarn.lock
Adding JSON backup download option to account creation flow.
> add json backup

- src/config/types.json
- src/pages/gift/claim/ClaimMain.js
- src/substrate-lib/Providers/ServiceProvider.js
- src/substrate-lib/Providers/balancePalletGiftProvider.js
- src/substrate-lib/Providers/bundleGiftProvider.js
- src/substrate-lib/Providers/giftPalletGiftProvider.js
- src/substrate-lib/Providers/txHandler.js
- src/substrate-lib/Providers/uniquesPalletGiftProvider.js
- src/substrate-lib/Providers/uniquesPalletProvider.js
- src/substrate-lib/SubstrateContext.js
- src/substrate-lib/substrateUtils.js
These changes are adding the support for claiming bundle gifts which might include balances and/or uniques NFTs.
> Add bundle gift provider to claim bundle gifts(NFT, balance)

- src/components/account/AccountSelector.js
- src/config/common.json
- src/config/development.json
- src/pages/gift/accounts/ConnectExtension.js
- src/pages/gift/accounts/LedgerWallet/LedgerInstructions.js
- src/pages/gift/claim/Claimed.js
- src/pages/gift/claim/ConnectAccount.js
- src/pages/gift/claim/VerifySecret.js
- src/pages/gift/claim/existing-account/ConnectExistingAccount.js
- src/pages/gift/claim/existing-account/EnterAccountAddress.js
- src/pages/gift/generate/GenerateGift.js
- src/pages/gift/generate/Landing.js
- src/pages/gift/generate/PresentGift.js
- src/substrate-lib/SubstrateContext.js
- src/substrate-lib/substrateUtils.js
Add theme config and theme config to let the app read the theme from config or query string and present the proper customization.
> Customize the app per theme

- src/components/account/AccountSelector.js
- src/polkadot-scss/_select.scss
- src/polkadot-scss/_variables.scss
- src/polkadot.scss
> Fix account selector height

- src/App.js
- src/index.css
- src/pages/gift/Footer.js
- src/pages/gift/about/AboutMain.js
- src/pages/gift/accounts/AccountOverview.js
- src/pages/gift/claim/ClaimMain.js
- src/pages/gift/claim/ConnectAccount.js
- src/pages/gift/generate/ConnectAccount.js
- src/pages/gift/generate/GenerateMain.js
- src/pages/gift/policy/PrivacyPolicy.js
- src/polkadot-scss/_footer.scss
- src/polkadot-scss/_privacypolicy.scss
- src/polkadot.scss
> Add Privacy Policy

- src/kusama-scss/_footer.scss
- src/pages/gift/footer/KusamaFooter.js
- src/pages/gift/footer/PolkadotFooter.js
- src/polkadot-scss/_footer.scss
> add paddind to footer to fix the footer overlap with card

- src/kusama-scss/_footer.scss
- src/pages/gift/footer/KusamaFooter.js
- src/pages/gift/footer/PolkadotFooter.js
- src/polkadot-scss/_footer.scss
> add paddind to footer to fix the footer overlap with cards

- src/pages/gift/accounts/ConnectExtension.js
- src/substrate-lib/SubstrateContext.js
- src/substrate-lib/extension.js
merging changes to show extension download button when user selected polkadot extension while extension is not installed on the browser
> show extension dowload button when not available

- src/substrate-lib/Providers/bundleFeeEstimationGiftProvider.js
Now that transferAll functionality is added to the network we can use that in place of fee estimation in bundle claims.
> switch to transferAll in bundleGiftProvider

- src/kusama-scss/_button.scss
- src/pages/gift/accounts/AccountOverview.js
- src/pages/gift/accounts/LedgerWallet/LedgerInstructions.js
> Account overview styling

- src/kusama-scss/_about.scss
- src/kusama-scss/_footer.scss
- src/kusama.scss
- src/pages/gift/about/AboutMain.js
- src/pages/gift/about/FAQ.js
- src/pages/gift/about/ProcessExplainerCard.js
- src/pages/gift/footer/Footer.js
- src/pages/gift/footer/KusamaFooter.js
- src/pages/gift/footer/PolkadotFooter.js
- src/pages/gift/policy/PrivacyPolicy.js
- src/polkadot-scss/_about.scss
- src/polkadot-scss/_bg.scss
- src/polkadot-scss/_footer.scss
- src/polkadot.scss
Changed background to white for the About page and have the card's background animated.
And made use of `giftTheme` on the About page.
> About Page background

- src/pages/gift/claim/existing-account/ConnectExistingAccount.js
> Remove manual address input for NFT campaign

- src/components/CardHeader.js
- src/config/common.json
- src/pages/gift/accounts/ConnectExtension.js
- src/pages/gift/generate/ConfirmGift.js
- src/pages/gift/generate/GenerateGift.js
- src/pages/gift/generate/GenerateMain.js
- src/pages/gift/generate/PresentGift.js
- src/polkadot-scss/_card.scss
- src/polkadot.scss
- src/substrate-lib/substrateUtils.js
- src/utils.js
This adds a gift confirm page to the generate flow.
> add confirm gift page

- package.json
- src/config/common.json
- src/pages/gift/header/KusamaHeader.js
- src/pages/gift/header/PolkadotHeader.js
- yarn.lock
> Add menu item for cousin network

- src/App.js
- src/pages/gift/about/AboutMain.js
- src/pages/gift/about/FAQ.js
- src/pages/gift/about/ProcessExplainerCard.js
- src/pages/gift/claim/ClaimMain.js
- src/pages/gift/claim/Claimed.js
- src/pages/gift/claim/ConnectAccount.js
- src/pages/gift/claim/VerifySecret.js
- src/pages/gift/claim/new-account/PresentAccountPhrase.js
- src/pages/gift/claim/new-account/VerifyAccountPhrase.js
- src/pages/gift/generate/ConfirmGift.js
- src/pages/gift/generate/GenerateGift.js
- src/pages/gift/generate/GenerateMain.js
- src/pages/gift/generate/Landing.js
- src/pages/gift/generate/PresentGift.js
- src/polkadot-scss/_landingpage.scss
> Copy update

- src/pages/gift/generate/ConfirmGift.js
- src/pages/gift/generate/GenerateGift.js
- src/substrate-lib/Providers/balancePalletGiftProvider.js
- src/substrate-lib/Providers/bundleGiftProvider.js
- src/substrate-lib/Providers/txCalls.js
await paymentInfo promises
calculate accurate fees for generate and confirm pages
refactor tx calls in a separate module
> await paymentInfo + refactor calls + accurate fees in cards

- src/pages/gift/generate/ConfirmGift.js
- src/pages/gift/generate/GenerateGift.js
- src/substrate-lib/Providers/balancePalletGiftProvider.js
- src/substrate-lib/Providers/bundleGiftProvider.js
- src/substrate-lib/Providers/txCalls.js
- yarn.lock
This PR adds simple remarks with events to the end to end gift process.
> Add Remarks to Gifts Process

- src/images/polkadot-circle-new.svg
- src/pages/gift/header/PolkadotHeader.js
- src/pages/gift/header/PolkadotNFTHeader.js
> Logo Update

- src/pages/gift/header/PolkadotHeader.js
- src/pages/gift/header/PolkadotNFTHeader.js
- src/polkadot.scss
set the logo size in a separate class.
> separate logo class

- .vscode/settings.json
- src/App.js
- src/config/common.json
- src/pages/gift/GiftSecretScanner.js
- src/pages/gift/claim/VerifySecret.js
- src/pages/gift/footer/PolkadotFooter.js
- src/substrate-lib/Providers/balancePalletGiftProvider.js
- src/substrate-lib/Providers/bundleGiftProvider.js
- src/utils.js
This adds a new utility page at <host>/giftScanner to resolve gift secret to gift account address with a link to an scanner website to scan the txs
> Add gift scan utility

- src/pages/gift/claim/VerifySecret.js
- src/pages/gift/claim/existing-account/EnterAccountAddress.js
- src/pages/gift/claim/new-account/DownloadJson.js
- src/pages/gift/claim/new-account/PresentAccountPhrase.js
- src/pages/gift/claim/new-account/VerifyAccountPhrase.js
- src/pages/gift/generate/ConfirmGift.js
- src/pages/gift/generate/GenerateGift.js
- src/polkadot.scss
> fix card height change when error box get visible

- src/config/development.json
- src/pages/gift/about/FAQ.js
- src/pages/gift/accounts/AccountOverview.js
- src/pages/gift/claim/ClaimMain.js
- src/pages/gift/claim/Claimed.js
- src/pages/gift/generate/GenerateMain.js
- src/pages/gift/header/PolkadotHeader.js
- src/substrate-lib/SubstrateContext.js
> make polkadot theme default + add westend theme

- src/pages/gift/footer/KusamaFooter.js
Quick PR to add legal disclosures to footer but also to test deployment procedure.
> added legal disclosures to footer
